# Generated by Django 3.1.1 on 2020-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/% Y/% m/% d/')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PR', 'Processing'), ('SC', 'Scheduled'), ('UN', 'Unable to Pay'), ('PA', 'Paid')], default='PR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
