# Generated by Django 3.1.1 on 2020-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
