# Generated by Django 3.1.1 on 2020-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billslist', '0002_bill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='image',
        ),
        migrations.AddField(
            model_name='bill',
            name='image_url',
            field=models.TextField(default='https://via.placeholder.com/480'),
        ),
    ]
