# Generated by Django 3.1.1 on 2020-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billslist', '0005_auto_20200929_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
