# Generated by Django 3.1.1 on 2020-09-29 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billslist', '0006_auto_20200929_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='processed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='original_url',
            field=models.TextField(default='https://via.placeholder.com/480x720'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='thumbnail_url',
            field=models.TextField(default='https://via.placeholder.com/80x120'),
        ),
    ]
